/*
# Todo

## Authentication / User Management:
  - User : {
      userId   : !ID     = REQUIRED, UNIQUE
      token    : !String = REQUIRED, UNIQUE ( generated by the backend on login, register )
      password : !String = REQUIRED
      todos    : ![Todo] = []
    }
  - /register   in:(id,password) out:(token)
  - /login      in:(id,password) out:(token)
  - /logout     in:(token)       out:()
  - /unregister in:(token)       out:()

## Todo-List:
  - Todo = {
      todoId : !ID      =          (Automatic)
      date   : !Date    = Date.now (Automatic)
      status : !Boolean = false
      text   : !String  = ''
    }
  - GET    /todo         in:(token)             out:([Todo])
  - POST   /todo         in:(token,Todo)        out:(Todo)
  - PATCH  /todo/:todoId in:(token,todoId,Todo) out:(Todo)
  - DELETE /todo/:todoId in:(token,todoId)      out:(*[Todo])
*/

const  crypto = require('crypto');
const   level = require('level');
const express = require('express');
const     app = express();
const  userDB = level('users');

// in reality pleas use a salt genrated by crypto.randomBytes
// OR: BETTER! a quantuum random generator
function generateToken ( userId, salt = "c765a454a7sc534as7c5437$" ) {
  return crypto
  .createHash('sha512')                      // << create hash machine
  .update(`${userId}:${Date.now()}:${salt}`) // << input
  .digest("hex");                            // hex = a765f57e65a65fec5765a...
};

function findUserByToken ( token ) {
  return new Promise( ( resolve, reject ) => {
    let foundUser = false;
    const stream = userDB.createValueStream();

    stream.on('data', function ( data ) {
      const user = JSON.parse( data );
      if ( user.token === token ){
        foundUser = true;
        stream.destroy();
        resolve(user);
      }
    });

    stream.on('close', function(){
      if ( ! foundUser ) reject('User not found');
    });
  });
}

async function readAuth(req,res,next) {
  const token = req.headers.authorization;
  if ( token ){
    try {
      req.user = await findUserByToken(token);
    } catch ( error ){
      console.error(
        'AUTH> validation failed:',
        error
      );
    }
  }
  next();
}

async function checkAuth(req,res,next) {
  if ( req.user ) next();
  else res.status(401).send('Not Authorized');
}

app.use( express.json() );
app.use( readAuth );

app.post( '/register', async (req,res) => {
  const { id, password } = req.body;
  // check if user id and password were provided
  if ( ! id || ! password )
    return res.status(400).send('Bad Request');
  // if we can actually get a user with this id,
  // it means that the userId is already taken
  try {
    await userDB.get(id);
    return res.status(401).send('Not Authorized');
  } catch ( error ){}
  // create user
  const user = {
    id,
    password,
    token: generateToken(id),
    todos: []
  };
  // save user to db
  await userDB.put( id, JSON.stringify(user) );
  // reply with new token
  res.send({ token: user.token });
});

app.post( '/login', async (req,res)=> {
  let user;
  const { id, password } = req.body;
  // check if user id and password were provided
  if ( ! id || ! password )
    return res.status(400).send('Bad Request');
  
  try {
    // check if user exists in the database
    user = JSON.parse( await userDB.get(id) );
  } catch ( error ){
    // else return a not found error
    return res.status(401).send('Not Authorized');
  }

  if ( user.password !== password ){
    return res.status(401).send('Not Authorized');
  }

  user.token = generateToken(id);
  await userDB.put( id, JSON.stringify(user) );
  res.send({ token: user.token });
});




app.post( '/logout', checkAuth, async (req,res)=> {
  const { user } = req;
  user.token = false;
  await userDB.put( user.id, JSON.stringify(user) );
  res.status(204).send();
});

app.post( '/unregister', checkAuth, async ({user},res)=> {
  await userDB.del(user.id);
  res.status(204).send();
});

const todoRouter = express.Router();

app.use('/todo',todoRouter);

todoRouter.use( checkAuth );

todoRouter.get( '/', async ({user},res)=> {
  res.send(user.todos);
});

todoRouter.post( '/', async ({body,user},res)=> {
  const { text = "", date = Date.now(), status = false } = body;
  const todo = { text, date, status, id: Date.now() };
  user.todos.push( todo );
  await userDB.put( user.id, JSON.stringify(user) );
  res.send(todo);
});

todoRouter.patch( '/:todoId', async (req,res)=> {
  const { user, body, params } = req;
  const todoId = Number( params.todoId );
  let     todo = user.todos.find( t => t.id === todoId );

  if ( ! todo )
    return res.status(404).send('Not Found!!!!111elf');

  const { text, date, status } = body;

  if (   text != undefined ) todo.text   = text;
  if (   date != undefined ) todo.date   = date;
  if ( status != undefined ) todo.status = status;

  await userDB.put( user.id, JSON.stringify(user) );
  res.send(todo);
});

todoRouter.delete( '/:todoId', async ({params,user},res)=> {

  const todoId = Number( params.todoId );
  user.todos = user.todos.filter( t => t.id !== todoId );

  await userDB.put( user.id, JSON.stringify(user) );
  res.status(204).send();
});

app.listen(4444,()=>{
  console.log("backend ready")
});